-- Migration 001: KYC fields on users table
ALTER TABLE users ADD COLUMN IF NOT EXISTS verification_stage INT DEFAULT 1;
ALTER TABLE users ADD COLUMN IF NOT EXISTS aadhaar_verified BOOLEAN DEFAULT FALSE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS kyc_provider VARCHAR(50);
ALTER TABLE users ADD COLUMN IF NOT EXISTS kyc_reference_id VARCHAR(100);
ALTER TABLE users ADD COLUMN IF NOT EXISTS aadhaar_name VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS aadhaar_dob DATE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS gst_number VARCHAR(15);
ALTER TABLE users ADD COLUMN IF NOT EXISTS gst_verified BOOLEAN DEFAULT FALSE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS pan_number VARCHAR(10);
ALTER TABLE users ADD COLUMN IF NOT EXISTS company_name VARCHAR(255);
